import os

#Global
SECRET_KEY = os.environ.get("SECRET_KEY")
TEMPLATES_AUTO_RELOAD = True
EXPLAIN_TEMPLATE_LOADING = False

# WTForms
WTF_CSRF_ENABLED = True
WTF_CSRF_TIME_LIMIT = None

# SQLAlchemy
SQLALCHEMY_DATABASE_URI = os.environ["DATABASE_URL"]
SQLALCHEMY_TRACK_MODIFICATIONS = False

# CORS
CORS_ORIGINS = "http://localhost:8080"
CORS_SEND_WILDCARD = True
